- plugin-gradle/CHANGELOG.md
- plugin-gradle/build.gradle
- plugin-gradle/example/build.gradle
- plugin-gradle/example/settings.gradle
- plugin-maven/CHANGELOG.md
- plugin-maven/build.gradle
- plugin-maven/example/pom.xml
- solstice/CHANGELOG.md
For integration testing. This exposed a problem in our maven metadata, which this PR hopefully fixes.
> Add examples of the gradle and maven plugins

- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeGradlePlugin.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeTask.java
- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/p2/CacheLocations.java
- solstice/src/main/java/dev/equo/solstice/p2/P2Client.java
- solstice/src/main/java/dev/equo/solstice/p2/WorkspaceRegistry.java
- solstice/src/test/java/dev/equo/solstice/p2/P2SessionTest.java
- solstice/src/testSetup1/java/dev/equo/solstice/MavenJarsNeededForTest.java
It improves performance and simplifies the code to have a central caching location. Copied the logic from Goomph's caching, which has worked well for a long time.
> Centralize cache and workspaces

- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- solstice/src/main/java/dev/equo/solstice/p2/JdtSetup.java
Maven plugin now uses the new p2 dependency resolver. Fixes
- #37
> Improve plugin-maven's dependency resolution

- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeTask.java
- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/ScriptExec.java
> Improve console launch

- EXAMPLES.md
- plugin-gradle/src/test/java/dev/equo/ide/gradle/P2MultitoolExamples.java
- plugin-gradle/src/test/java/dev/equo/ide/gradle/__snapshots__/P2MultitoolExamples.snap
I keep google-digging for the same info. Added `EXAMPLES.md` to centralize information about existing p2 projects.
> Add a list of working examples

- .github/workflows/gradle-build.yml
- gradle.properties
- plugin-gradle/CHANGELOG.md
- plugin-gradle/P2DEPS.md
- plugin-gradle/README.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeGradlePlugin.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2DepsExtension.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2DepsPlugin.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2ModelDsl.java
- plugin-gradle/src/test/java/dev/equo/ide/gradle/P2DepsPluginTest.java
For compiling against p2 dependencies.
> Add `dev.equo.p2deps` plugin

- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeTask.java
- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
- solstice/src/main/java/dev/equo/ide/IdeHook.java
- solstice/src/main/java/dev/equo/ide/IdeHookBranding.java
- solstice/src/main/java/dev/equo/ide/IdeHookInstantiated.java
- solstice/src/main/java/dev/equo/ide/IdeHookLockFile.java
- solstice/src/main/java/dev/equo/ide/IdeLockFile.java
- solstice/src/main/java/dev/equo/ide/Launcher.java
IDE plugins now know if it is a "clean" first invocation or not. Also improvements to branding and lockfile to improve the experience problems in
- #44
> Suggest cleaning IDE

- plugin-gradle/CHANGELOG.md
- plugin-gradle/README.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeTask.java
- plugin-gradle/src/test/java/dev/equo/ide/gradle/__snapshots__/EquoIdeTest.snap
- plugin-maven/CHANGELOG.md
- plugin-maven/README.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- plugin-maven/src/test/java/dev/equo/ide/maven/__snapshots__/LaunchTest.snap
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
This PR makes it easy to remote debug the launched IDE.
> Attach remote debugger to launched IDE

- plugin-gradle/CHANGELOG.md
- plugin-gradle/README.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeTask.java
- plugin-gradle/src/test/java/dev/equo/ide/gradle/EquoIdeTest.java
- plugin-gradle/src/test/java/dev/equo/ide/gradle/__snapshots__/EquoIdeTest.snap
- plugin-maven/README.md
- solstice/CHANGELOG.md
- solstice/build.gradle
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
- solstice/src/main/java/dev/equo/solstice/BundleContextDelegate.java
- solstice/src/main/java/dev/equo/solstice/BundleContextSolstice.java
- solstice/src/main/java/dev/equo/solstice/Capability.java
- solstice/src/main/java/dev/equo/solstice/NestedJars.java
- solstice/src/main/java/dev/equo/solstice/ShimBundleWiring.java
- solstice/src/main/java/dev/equo/solstice/ShimLocation.java
- solstice/src/main/java/dev/equo/solstice/ShimStorage.java
- solstice/src/main/java/dev/equo/solstice/Solstice.java
- solstice/src/main/java/dev/equo/solstice/SolsticeIdeBootstrapServices.java
- solstice/src/main/java/dev/equo/solstice/Unchecked.java
- solstice/src/test/java/dev/equo/ide/SolsticeSmokeTest.java
In an effort to fix some last remaining issues with Atomos, I tried to see if we could get pure-Solstice up to a higher level of compatibility. It's a lot easier now because we can toggle back and forth with Atomos to see where behavior differs.
So far this PR has fixes for
- #33
but it looks like we might not need to set Atomos as the default after all. We'll see.
> Fix pure-Solstice

- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- solstice/src/main/java/dev/equo/ide/Launcher.java
- solstice/src/main/java/dev/equo/ide/ScriptExec.java
- More attempts to fully resolve #44 on maven linux and windows
> Try some maven startup tweaks

- plugin-gradle/CHANGELOG.md
- plugin-maven/CHANGELOG.md
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/BundleContextAtomos.java
- solstice/src/main/java/dev/equo/solstice/BundleContextShim.java
- solstice/src/main/java/dev/equo/solstice/ShimBundle.java
- solstice/src/main/java/dev/equo/solstice/SolsticeManifest.java
Fixes JUnit launching inside the launched IDE.
- Closes #78
> Fix JUnit launching

- plugin-maven/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/ScriptExec.java
> Fix maven launching

- CATALOG.md
- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2ModelDslWithCatalog.java
- plugin-maven/CHANGELOG.md
- plugin-maven/README.md
- plugin-maven/src/main/java/dev/equo/ide/maven/AbstractP2MojoWithCatalog.java
- plugin-maven/src/test/java/dev/equo/ide/maven/__snapshots__/LaunchTest.snap
- plugin-maven/src/test/java/dev/equo/ide/maven/__snapshots__/ListTest.snap
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
- solstice/src/main/java/dev/equo/ide/Catalog.java
- solstice/src/main/java/dev/equo/solstice/Capability.java
- solstice/src/main/java/dev/equo/solstice/ShimIdeBootstrapServices.java
- solstice/src/main/java/dev/equo/solstice/Solstice.java
- solstice/src/main/java/dev/equo/solstice/platform/Handler.java
> Add m2e to the catalog

- plugin-gradle/CHANGELOG.md
- plugin-maven/CHANGELOG.md
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
- solstice/src/main/java/dev/equo/solstice/Unimplemented.java
I broke a few things in the plugins while getting Solstice to 1.0 for Spotless integration.
> Fix various elements of IDE launching

- plugin-gradle/CHANGELOG.md
- plugin-maven/CHANGELOG.md
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/IdeHookBranding.java
> Fix the missing icon

- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/p2/P2Client.java
- solstice/src/test/java/dev/equo/solstice/p2/P2Test.java
- solstice/src/test/java/dev/equo/solstice/p2/__snapshots__/P2Test.snap
> Fix p2 client on the placeholder 4.28 update site

- plugin-gradle/CHANGELOG.md
- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- plugin-maven/src/main/java/dev/equo/ide/maven/Welcome.java
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/Catalog.java
- solstice/src/main/java/dev/equo/ide/CatalogDsl.java
- solstice/src/main/java/dev/equo/ide/IdeHookWelcome.java
- solstice/src/welcome/java/dev/equo/ide/WelcomeImpl.java
User can do it manually, or we set a default based on catalog entries.
> Set the startup perspective

- patch-equinox-4.27/build.gradle
- patch-equinox-4.27/src/main/java/org/eclipse/osgi/internal/framework/EquinoxBundle.java
- plugin-gradle/CHANGELOG.md
- plugin-maven/CHANGELOG.md
- settings.gradle
- solstice/CHANGELOG.md
- solstice/build.gradle
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
- solstice/src/main/java/dev/equo/ide/Patch.java
- solstice/src/main/java/dev/equo/solstice/BundleContextAtomos.java
- solstice/src/main/java/dev/equo/solstice/ShimBundle.java
- solstice/src/main/java/dev/equo/solstice/ShimIdeBootstrapServices.java
- solstice/src/main/java/dev/equo/solstice/SignedJars.java
- solstice/src/main/java/dev/equo/solstice/Solstice.java
- solstice/src/main/java/dev/equo/solstice/SolsticeManifest.java
- solstice/src/main/java/dev/equo/solstice/p2/MavenCentralMapping.java
> Fix PDE under Atomos

- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeExtension.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeGradlePlugin.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoIdeTask.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/EquoListTask.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2DepsExtension.java
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2ModelDslWithCatalog.java
- plugin-maven/CHANGELOG.md
- plugin-maven/src/main/java/dev/equo/ide/maven/AbstractP2Mojo.java
- plugin-maven/src/main/java/dev/equo/ide/maven/AbstractP2MojoWithCatalog.java
- plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java
- plugin-maven/src/main/java/dev/equo/ide/maven/ListMojo.java
- plugin-maven/src/main/java/dev/equo/ide/maven/WorkspaceProp.java
- plugin-maven/src/test/java/dev/equo/ide/maven/__snapshots__/LaunchTest.snap
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java
- solstice/src/main/java/dev/equo/ide/Catalog.java
- solstice/src/main/java/dev/equo/ide/CatalogDsl.java
- solstice/src/main/java/dev/equo/ide/CatalogJdt.java
- solstice/src/main/java/dev/equo/ide/CatalogPde.java
- solstice/src/main/java/dev/equo/ide/CatalogPlatform.java
- solstice/src/main/java/dev/equo/ide/WorkspaceInit.java
This PR makes it possible to set preferences in the IDE workspace, both arbitrary preferences and convenient DSL for specific properties.
> Set preferences in the IDE workspace

- CATALOG.md
- plugin-gradle/CHANGELOG.md
- plugin-gradle/README.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2ModelDslWithCatalog.java
- plugin-maven/CHANGELOG.md
- plugin-maven/README.md
- plugin-maven/src/main/java/dev/equo/ide/maven/AbstractP2MojoWithCatalog.java
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/ide/CatalogDsl.java
- solstice/src/main/java/dev/equo/ide/CatalogJdt.java
- solstice/src/main/java/dev/equo/ide/CatalogPlatform.java
Add the preferences below.
- platform
- showLineNumbers
- showWhitespace
- showLineEndings
- jdt
- classpathVariable
> Add more preferences

- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/p2/CacheLocations.java
We're still failing in the same way we were previously.
- https://github.com/diffplug/spotless/issues/1687#issuecomment-1560529717
> Fix cache location when we can't determine the home directory.

- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/main/java/dev/equo/ide/gradle/P2DepsExtension.java
> Update the `p2deps` plugin to allow adding deps to multiple configurations at once

- plugin-gradle/README.md
> Add docs for `p2deps`

- plugin-gradle/CHANGELOG.md
- plugin-maven/CHANGELOG.md
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/p2/JarCache.java
- solstice/src/main/java/dev/equo/solstice/p2/P2Client.java
> Failed to download p2repo when url contains username and password

- .github/workflows/gradle-build.yml
- gradle/blowdryer-scripts/snapshot-testing.gradle
- plugin-gradle/CHANGELOG.md
- plugin-gradle/src/test/java/dev/equo/ide/gradle/GradleHarness.java
- plugin-maven/CHANGELOG.md
- plugin-maven/src/test/java/dev/equo/ide/maven/MavenHarness.java
- settings.gradle
- solstice/CHANGELOG.md
- solstice/src/main/java/dev/equo/solstice/p2/LockFile.java
- fixes https://github.com/equodev/equo-ide/issues/182
> Don't error on parallel in-process downloads
